<a href="https://colab.research.google.com/github/LindsClar/Capstone_2/blob/main/Capstone_Two_Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Organize your data to streamline the next steps of your capstone
#GOAL compare TX market to CA
#load imports
import pandas as pd
import numpy as np
import os

In [ ]:
#DATA COLLECTION: load data ie. read_csv()
df = pd.read_csv('USRealEstateTrends.csv')
# see a sample of the data
df.head()

,RegionID,SizeRank,RegionName,StateName,2018-02-HomeValue,2018-02-DaysPending,2018-02-CutRaw,2018-03-HomeValue,2018-03-DaysPending,2018-03-CutRaw,...,2024-02-CutRaw,2024-03-HomeValue,2024-03-DaysPending,2024-03-CutRaw,2024-04-HomeValue,2024-04-DaysPending,2024-04-CutRaw,2024-05-HomeValue,2024-05-DaysPending,2024-05-CutRaw
0,102001,0,United States,NaN,225746.614318,52.0,7600.0,227155.648994,48.0,8900.0,...,10000.0,357374.362080,42.0,10000.0,359240.114070,38.0,10000.0,360681.294250,37.0,10000.0
1,394913,1,"New York, NY",NY,468313.430126,68.0,16000.0,470102.249154,63.0,19751.5,...,25000.0,646508.747102,55.0,25000.0,652619.099940,51.0,26000.0,657279.223513,47.0,30000.0
2,753899,2,"Los Angeles, CA",CA,629019.165765,33.0,20000.0,636850.139417,31.0,20000.0,...,30000.5,952665.578913,32.0,34000.0,956266.687926,29.0,40012.0,962388.491425,28.0,40000.0
3,394463,3,"Chicago, IL",IL,229741.266973,52.0,8000.0,231317.183706,42.0,9100.0,...,10000.0,316875.294320,29.0,10000.0,319764.144323,25.0,10000.0,321897.252361,23.0,10000.0
4,394514,4,"Dallas, TX",TX,241533.231800,46.0,8562.0,243401.180622,42.0,9900.0,...,10000.0,379972.349667,42.0,10000.0,380957.392395,38.0,10000.0,381103.625851,38.0,10000.0

In [ ]:
#DATA DEFINITION
#renaming the columns in df
#Should I rename all the columns? Should I eliminate more columns or how can I combine thme by year?
df.rename(index=str, columns={'RegionName' : 'Location', 'StateName':'State', '2018-02-HomeValue':'2018_Feb_Cost', '2018-02-DaysPending':'2018_Feb_DaysPending'}, inplace=True)
df.head()

#dropping NaN
df.dropna(inplace=True)
df.head()

,RegionID,SizeRank,Location,State,2018_Cost,2018_Feb_DaysPending,2018-02-CutRaw,2018-03-HomeValue,2018-03-DaysPending,2018-03-CutRaw,...,2024-02-CutRaw,2024-03-HomeValue,2024-03-DaysPending,2024-03-CutRaw,2024-04-HomeValue,2024-04-DaysPending,2024-04-CutRaw,2024-05-HomeValue,2024-05-DaysPending,2024-05-CutRaw
1,394913,1,"New York, NY",NY,468313.430126,68.0,16000.0,470102.249154,63.0,19751.5,...,25000.0,646508.747102,55.0,25000.0,652619.099940,51.0,26000.0,657279.223513,47.0,30000.0
2,753899,2,"Los Angeles, CA",CA,629019.165765,33.0,20000.0,636850.139417,31.0,20000.0,...,30000.5,952665.578913,32.0,34000.0,956266.687926,29.0,40012.0,962388.491425,28.0,40000.0
3,394463,3,"Chicago, IL",IL,229741.266973,52.0,8000.0,231317.183706,42.0,9100.0,...,10000.0,316875.294320,29.0,10000.0,319764.144323,25.0,10000.0,321897.252361,23.0,10000.0
4,394514,4,"Dallas, TX",TX,241533.231800,46.0,8562.0,243401.180622,42.0,9900.0,...,10000.0,379972.349667,42.0,10000.0,380957.392395,38.0,10000.0,381103.625851,38.0,10000.0
5,394692,5,"Houston, TX",TX,208651.872272,51.0,10000.0,209394.157749,45.0,10000.0,...,10000.0,309138.260511,53.0,10000.0,310167.057071,47.0,10000.0,310706.915311,46.0,10000.0

In [ ]:
#DATA ORGANIZATION - Adding this to github

In [ ]:

#extract all information for CA
CA_df = df.loc[df['State'] == 'CA']
print(CA_df.head())

#Extracting NaN from CA
#CA_df.dropna(inplace=True)


#extract all information from TX
TX_df = df.loc[df['State']== 'TX']
print(TX_df.head())

#Extracting NaN from TX
#TX_df.dropna(inplace=True)

    RegionID  SizeRank           Location State      2018_Cost  \
2     753899         2    Los Angeles, CA    CA  629019.165765
12    395057        12  San Francisco, CA    CA  915915.834585
17    395056        17      San Diego, CA    CA  586462.807159
62    394357        63    Bakersfield, CA    CA  212531.666950
70    394952        71         Oxnard, CA    CA  603755.944417

    2018_Feb_DaysPending  2018-02-CutRaw  2018-03-HomeValue  \
2                   33.0         20000.0      636850.139417
12                  21.0         39000.0      925972.955108
17                  33.0         15000.0      588610.353201
62                  51.0          7000.0      213905.260766
70                  34.0         11000.0      606107.615916

    2018-03-DaysPending  2018-03-CutRaw  ...  2024-02-CutRaw  \
2                  31.0         20000.0  ...         30000.5
12                 19.0         45112.0  ...         30000.0
17                 33.0         15000.0  ...         25000.0
62                 48.0          7100.0  ...         10000.0
70                 32.0         14995.0  ...         28000.0

    2024-03-HomeValue  2024-03-DaysPending  2024-03-CutRaw  2024-04-HomeValue  \
2        9.526656e+05                 32.0         34000.0       9.562667e+05
12       1.158459e+06                 25.0         36000.0       1.170446e+06
17       9.387990e+05                 25.0         26000.0       9.492897e+05
62       3.491466e+05                 38.0         10000.0       3.513458e+05
70       8.597405e+05                 25.0         25000.0       8.666152e+05

    2024-04-DaysPending  2024-04-CutRaw  2024-05-HomeValue  \
2                  29.0         40012.0       9.623885e+05
12                 23.0         40000.0       1.183272e+06
17                 24.0         30000.0       9.582660e+05
62                 33.0         10000.0       3.535951e+05
70                 23.0         25000.0       8.734901e+05

    2024-05-DaysPending  2024-05-CutRaw
2                  28.0         40000.0
12                 24.0         44001.0
17                 23.0         26000.0
62                 32.0         10000.0
70                 23.0         30000.0

[5 rows x 232 columns]
     RegionID  SizeRank            Location State      2018_Cost  \
4      394514         4          Dallas, TX    TX  241533.231800
5      394692         5         Houston, TX    TX  208651.872272
66     394843        67         McAllen, TX    TX  105348.864431
126    394502       129  Corpus Christi, TX    TX  166118.001594
127    394421       130     Brownsville, TX    TX  119749.603873

     2018_Feb_DaysPending  2018-02-CutRaw  2018-03-HomeValue  \
4                    46.0          8562.0      243401.180622
5                    51.0         10000.0      209394.157749
66                   87.0          5000.0      106010.935188
126                  77.0          5900.0      166855.611359
127                  83.0          5400.0      119754.732368

     2018-03-DaysPending  2018-03-CutRaw  ...  2024-02-CutRaw  \
4                   42.0          9900.0  ...         10000.0
5                   45.0         10000.0  ...         10000.0
66                  91.0          5000.0  ...          7000.0
126                 80.0          7049.5  ...         10000.0
127                 75.0          5400.0  ...         10000.0

     2024-03-HomeValue  2024-03-DaysPending  2024-03-CutRaw  \
4        379972.349667                 42.0         10000.0
5        309138.260511                 53.0         10000.0
66       185919.564594                 88.0          7000.0
126      219816.882167                 71.0         10000.0
127      189972.726719                 75.0         10000.0

     2024-04-HomeValue  2024-04-DaysPending  2024-04-CutRaw  \
4        380957.392395                 38.0         10000.0
5        310167.057071                 47.0         10000.0
66       186698.659466                 95.0          8000.0
126      220529.977431                 63.0         10000.0
127      191397.769580                106.0         10000.0

     2024-05-HomeValue  2024-05-DaysPending  2024-05-CutRaw
4        381103.625851                 38.0         10000.0
5        310706.915311                 46.0         10000.0
66       187201.083509                103.0          7000.0
126      221027.292386                 69.0         10000.0
127      192062.314551                 91.0         10000.0

[5 rows x 232 columns]

In [ ]:
#DATA DEFINITION

In [ ]:
#DATA CLEANING